// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQe-0-q45L9Kb-DrRvHGwOOwnEyMlv4Tc',
    appId: '1:77730487546:web:8916bc81c62844c7087d43',
    messagingSenderId: '77730487546',
    projectId: 'tarea03pmdm',
    authDomain: 'tarea03pmdm.firebaseapp.com',
    storageBucket: 'tarea03pmdm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlSJR3NMUfa7cuF_AdW2x1tiB8noDq2rI',
    appId: '1:77730487546:android:fc6eba150442d5cc087d43',
    messagingSenderId: '77730487546',
    projectId: 'tarea03pmdm',
    storageBucket: 'tarea03pmdm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi-CIgfGzLNRrKCfVuvXu0gQw6vb-QlCQ',
    appId: '1:77730487546:ios:6a3d94f2af3b089f087d43',
    messagingSenderId: '77730487546',
    projectId: 'tarea03pmdm',
    storageBucket: 'tarea03pmdm.firebasestorage.app',
    iosBundleId: 'com.example.pmdm2526T03',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi-CIgfGzLNRrKCfVuvXu0gQw6vb-QlCQ',
    appId: '1:77730487546:ios:6a3d94f2af3b089f087d43',
    messagingSenderId: '77730487546',
    projectId: 'tarea03pmdm',
    storageBucket: 'tarea03pmdm.firebasestorage.app',
    iosBundleId: 'com.example.pmdm2526T03',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQe-0-q45L9Kb-DrRvHGwOOwnEyMlv4Tc',
    appId: '1:77730487546:web:8739769ea8fb24dc087d43',
    messagingSenderId: '77730487546',
    projectId: 'tarea03pmdm',
    authDomain: 'tarea03pmdm.firebaseapp.com',
    storageBucket: 'tarea03pmdm.firebasestorage.app',
  );
}
